name: run

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - run: python fetch.py

      - run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add data.db
          git commit -m "update" || echo "no change"
          git push
